services:
  mysql:
    image: mysql:8.3.0
    container_name: inventory_service
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: changeinprod
    volumes:
      - mysql_inventory_data:/var/lib/mysql
      - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  mysql_inventory_data: